name: Rust Init
description: Initialize a Rust project with a basic structure and dependencies.
inputs:
  git_token:
    description: 'Token to authenticate for git'
    required: false
  packages:
    description: 'Packages to install per OS, see .github/ci-configs/rust-default.yml'
    required: false
    default: ''
  ref:
    description: 'Ref to checkout'
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        token: ${{ inputs.git_token || github.token }}
        ref: ${{ inputs.ref }}
    - name: cache
      uses: ubicloud/rust-cache@v2
      with:
        cache-on-failure: 'true'
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable,nightly
        components: rustfmt,clippy
    # - name: Install nightyly
    #   id: toolchain-nightly
    #   uses: dtolnay/rust-toolchain@nightly
    #   with:
    #     components: "rustfmt,clippy"
    # - name: Install stable
    #   id: toolchain-stable
    #   shell: bash
    #   run: |
    #     rustup toolchain install stable --component clippy --profile minimal --no-self-update
    #     rustup default stable
    #     echo "name=stable" >> $GITHUB_OUTPUT
    - name: Debug versions
      shell: bash
      run: |
        cargo +nightly --version
        cargo +stable --version

    - name: packages
      shell: bash
      if: ${{ inputs.packages }}
      run: |
        case $RUNNER_OS in
          Linux)
            packages=${{ fromJSON(inputs.packages).Linux }}
            _os='linux'
            ;;
          macOS)
            _os='darwin'
            packages=${{ fromJSON(inputs.packages).macOS }}
            ;;

          *)
            echo "Cannot handle OS of type $RUNNER_OS"
            echo "Expected one of: [ Linux macOS ]"
            exit 0
            ;;
        esac

        if [ -z "$packages" ]; then
          echo "No packages to install"
          exit 0
        fi

        echo "Installing packages: $packages"
        sudo $packages
