name: Rust Init
description: Initialize a Rust project with a basic structure and dependencies.
inputs:
  git_token:
    description: 'Token to authenticate for git'
    required: false
  ubuntu_packages:
    description: 'Packages to install'
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        token: ${{ inputs.git_token || github.token }}
    - name: cache
      uses: ubicloud/rust-cache@v2
      with:
        cache-on-failure: 'true'
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable,nightly
        components: rustfmt,clippy
    # - name: Install nightyly
    #   id: toolchain-nightly
    #   uses: dtolnay/rust-toolchain@nightly
    #   with:
    #     components: "rustfmt,clippy"
    # - name: Install stable
    #   id: toolchain-stable
    #   shell: bash
    #   run: |
    #     rustup toolchain install stable --component clippy --profile minimal --no-self-update
    #     rustup default stable
    #     echo "name=stable" >> $GITHUB_OUTPUT
    - name: Debug versions
      shell: bash
      run: |
        cargo +nightly --version
        cargo +stable --version

    - name: packages
      shell: bash
      if: ${{ inputs.ubuntu_packages }}
      run: |
        if ! which apt-get ; then
           echo "No apt-get found"
           exit 0
        fi
        if [ -x "$(which apt-get)" ] ; then
          set -x
          sudo apt-get install -y ${{ inputs.ubuntu_packages }}
        fi
