name: Rust CI Config
description: Merge Rust CI Config
inputs:
  git_token:
    description: 'Token to authenticate for git'
    required: false
  runner:
    description: 'Runner to use for CI'
    required: false

outputs:
  config:
    description: 'Configuration JSON output'
    value: ${{ steps.merge.outputs.config }}
runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        token: ${{ inputs.git_token || github.token }}
    - name: Check if yq exists
      id: check-yq
      shell: bash
      run: |
        if command -v yq &> /dev/null; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi
    - name: Setup yq
      if: steps.check-yq.outputs.exists == 'false'
      uses: mikefarah/yq@v4
    - name: Merge YAML configs
      shell: bash
      run: |
        # env | grep GITHUB | sort
        BRANCH_ACTION_CONFIG=""
        BRANCH_CONFIG=""
        if [ -d  "${{ github.action_path }}/../../ci-configs/rust" ]; then
          BRANCH_ACTION_CONFIG="${{ github.action_path }}/../../ci-configs/rust/*.yml"
        fi
        if [ -d "../../ci-configs/$GITHUB_REF_NAME" ]; then
          BRANCH_CONFIG="../../ci-configs/$GITHUB_REF_NAME/rust*.yml"
        fi
        echo "BRANCH_ACTION_CONFIG=$BRANCH_ACTION_CONFIG"
        echo "BRANCH_CONFIG=$BRANCH_CONFIG"
        ls $BRANCH_ACTION_CONFIG || echo no branch action config files found
        ls $BRANCH_CONFIG || echo no repo branch config files found
        ls .github/ci-configs/rust*.yml || echo no repo config files find
        yq eval-all '. as $item ireduce ({}; . * $item)' \
          "${{ github.action_path }}/../../ci-configs/rust-default.yml" \
          $BRANCH_ACTION_CONFIG \
          $BRANCH_CONFIG \
          .github/ci-configs/rust*.yml \
          -o json > merged.json
    - name: merge
      id: merge
      uses: carteramesh/ci@main
      with:
        config: merged.json
        runner: ${{ inputs.runner }}
