name: Rust CI Config
description: Merge Rust CI Config
inputs:
  git_token:
    description: 'Token to authenticate for git'
    required: false
  arm64:
    default: "ubicloud-standard-8-arm"
    required: false
  amd64:
    default: "ubicloud-standard-4"
    required: false
outputs:
  config:
    description: 'Configuration JSON output'
    value: ${{ steps.config.outputs.config }}
runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        token: ${{ inputs.git_token || github.token }}
    - name: generate
      id: generate
      uses: dougefresh/ci@main
    - name: replace runners
      id: config
      shell: bash
      run: |
        CONFIG="$(echo '${{ steps.generate.outputs.config }}' | sed \
            -e 's/vars.RUNNER_ARM64/${{ inputs.arm64 }}/g' \
            -e 's/vars.RUNNER_AMD64/${{ inputs.amd64 }}/g')"
        echo "config=$CONFIG" >> $GITHUB_OUTPUT
