name: Rust CI Config
description: Merge Rust CI Config
inputs:
  git_token:
    description: 'Token to authenticate for git'
    required: false
  arm64:
    default: "ubicloud-standard-8-arm"
    required: false
  amd64:
    default: "ubicloud-standard-4"
    required: false
outputs:
  config:
    description: 'Configuration JSON output'
    value: ${{ steps.config.outputs.config }}
runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        token: ${{ inputs.git_token || github.token }}
    - name: generate
      id: generate
      uses: kiro-generator/ci@main
    - name: replace runners
      id: config
      shell: bash
      env:
        CONFIG_JSON: ${{ steps.generate.outputs.config }}
        ARM64_RUNNER: ${{ inputs.arm64 }}
        AMD64_RUNNER: ${{ inputs.amd64 }}
      run: |
        CONFIG="$(echo "$CONFIG_JSON" | sed \
            -e "s/vars.RUNNER_ARM64/$ARM64_RUNNER/g" \
            -e "s/vars.RUNNER_AMD64/$AMD64_RUNNER/g")"
        echo "config=$CONFIG" >> $GITHUB_OUTPUT
