name: ci-config
description: config ci config
author: Cartera Mesh
branding:
  icon: scissors
  color: black
outputs:
  config:
    description: JSON string of the config
    value: ${{ steps.generate.outputs.config }}
runs:
  using: composite
  steps:
    - name: setup bun
      uses: oven-sh/setup-bun@v2
    - id: generate
      name: generate
      shell: bash
      run: |
        if [ ! -f .github/rust-ci.ts ]; then
          echo "::error::Missing .github/rust-ci.ts config file"
          exit 1
        fi
        cp -v .github/rust-ci.ts ${{ github.action_path }}/.github/
        cat ${{ github.action_path }}/.github/rust-ci.ts
        cd ${{ github.action_path }}
        CONFIG="$(bun run ./scripts/generate-rust.ts | jq . --compact-output )"
        echo "config=$CONFIG" >> $GITHUB_OUTPUT
