env:
  MEMO: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} ${{ github.job }}'
  JOB_URL: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
  RUST_LOG: "${{ fromJSON(inputs.config).global.rustlog || 'info' }}"
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: check test
jobs:
  coverage:
    runs-on: ${{ matrix.os }}
    if: ${{ fromJSON(inputs.config).jobs.coverage.if }}
    name: coverage / ${{ matrix.features }} / ${{ matrix.os }} / ${{ matrix.toolchain }}
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(inputs.config).jobs.coverage.os }}
        features: ${{ fromJSON(inputs.config).jobs.coverage.features }}
    steps:
      - name: Init
        uses: carteramesh/ci/.github/actions/rust-init@main
        with:
          ubuntu_packages: ${{ fromJSON(inputs.config).global.ubuntu_packages }}
      - name: fireblocks
        uses: carteramesh/fireblocks-config-action@main
        if: ${{ fromJSON(inputs.config).global.fireblocks.enabled }}
        with:
          fireblocks-secret: |
            ${{ secrets.FIREBLOCKS_SECRET }}
          fireblocks-api-key: ${{ secrets.FIREBLOCKS_API_KEY }}
          fireblocks-endpoint: ${{ vars.FIREBLOCKS_ENDPOINT }}
          solana-rpc-url: ${{ secrets.RPC_URL }}
          commitment: 'finalized'
          set-env-vars: 'false'
      - name: llvm-tools
        shell: bash
        run: |
          rustup default ${{ matrix.toolchain }}
          rustup component add llvm-tools-preview
          cargo install cargo-llvm-cov
      - name: cargo generate-lockfile
        if: hashFiles('Cargo.lock') == ''
        run: cargo generate-lockfile
      - name: llvm-cov (${{ matrix.features }})
        run: |
          ${{ fromJSON(inputs.config).jobs.coverage.run }}
        env:
          FEATURES: ${{ matrix.features }}
          CARGO_ARGS: ${{ fromJSON(inputs.config).jobs.coverage.args || '' }}
      - name: Record Rust version
        run: echo "RUST=$(rustc --version)" >> "$GITHUB_ENV"
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov-${{ matrix.features }}.info
          flags: ${{ matrix.features }}
          env_vars: OS,RUST
  fmt:
    runs-on: ${{ fromJSON(inputs.config).runner }}
    name: fmt
    if: ${{ fromJSON(inputs.config).jobs.fmt.if }}
    steps:
      - name: Init
        uses: carteramesh/ci/.github/actions/rust-init@main
      - name: fmt
        run: |
          ${{ fromJSON(inputs.config).jobs.fmt.run }}
  clippy:
    runs-on: ${{ matrix.os }}
    if: ${{ fromJSON(inputs.config).jobs.clippy.if }}
    name: ${{ matrix.toolchain }} / clippy / ${{ matrix.features }} / ${{ matrix.os }}
    permissions:
      contents: read
      checks: write
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(inputs.config).jobs.clippy.matrix }}
    steps:
      - name: Init
        uses: carteramesh/ci/.github/actions/rust-init@main
        with:
          ubuntu_packages: ${{ fromJSON(inputs.config.global.ubuntu_packages) }}
      - name: ${{ matrix.toolchains }} cargo clippy (${{ matrix.features }})
        uses: giraffate/clippy-action@v1
        with:
          reporter: 'github-pr-check'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tool_name: clippy-${{ matrix.toolchains }}-${{ matrix.features }}
          clippy_flags: ${{ matrix.features != 'default' && format('--features {0}', matrix.features) || '' }}

  semver:
    runs-on: ${{ fromJSON(inputs.config).runner }}
    name: semver
    if: ${{ fromJSON(inputs.config).jobs.semver.if }}
    steps:
      - name: Init
        uses: carteramesh/ci/.github/actions/rust-init@main
        with:
          ubuntu_packages: ${{ fromJSON(inputs.config).global.ubuntu_packages }}
      - name: cargo-semver-checks
        uses: obi1kenobi/cargo-semver-checks-action@v2
        # with:
        # feature-group: ${{ matrix.features != 'default' && matrix.features || 'default-features' }}

  hack:
    # cargo-hack checks combinations of feature flags to ensure that features are all additive
    # which is required for feature unification
    runs-on: ${{ fromJSON(inputs.config).runner }}
    name: hack
    if: ${{ fromJSON(inputs.config).jobs.hack.if }}
    steps:
      - name: Init
        uses: carteramesh/ci/.github/actions/rust-init@main
        with:
          ubuntu_packages: ${{ fromJSON(inputs.config).global.ubuntu_packages }}
      - name: Install cargo-hack
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-hack
          locked: false
      # intentionally no target specifier; see https://github.com/jonhoo/rust-ci-conf/pull/4
      # --feature-powerset runs for every combination of features
      - name: cargo hack
        run: cargo hack --feature-powerset check

  doc:
    runs-on: ${{ fromJSON(inputs.config).runner }}
    name: doc
    if: ${{ fromJSON(inputs.config).jobs.doc.if }}
    steps:
      - name: Init
        uses: carteramesh/ci/.github/actions/rust-init@main
        with:
          ubuntu_packages: ${{ fromJSON(inputs.config).global.ubuntu_packages }}
      - name: Install cargo-docs-rs
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-docs-rs
          locked: false
      - name: cargo docs-rs
        run: |
          ${{ fromJSON(inputs.config).jobs.cargo-docs.run }}

  cargo-sort:
    runs-on: ${{ fromJSON(inputs.config).runner }}
    name: cargo-sort
    if: ${{ fromJSON(inputs.config).jobs.cargo-sort.if }}
    steps:
      - name: Init
        uses: carteramesh/ci/.github/actions/rust-init@main
      - name: Install cargo-sort
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-sort
          locked: false
      - name: Check `Cargo.toml` sort
        run: |
          ${{ fromJSON(inputs.config).jobs.cargo-sort.run }}

  dependencies:
    runs-on: ${{ fromJSON(inputs.config).runner }}
    name: check unused deps
    if: ${{ fromJSON(inputs.config).jobs.dependencies.if }}
    steps:
      - name: Init
        uses: carteramesh/ci/.github/actions/rust-init@main
      - name: Install cargo-machete
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-machete
          locked: false
      - name: Check unused Cargo dependencies
        run: |
          ${{ fromJSON(inputs.config).jobs.dependencies.run }}
