ai:
  enabled: true
  allowed_bots: '*'
  claude_args: ''
  use_sticky_comment: false
  track_progress: true
  prompt: |
    REPO: ${{ github.repository }}
    PR NUMBER: ${{ github.event.pull_request.number }}

    Perform a comprehensive code review with the following focus areas:
    Provide detailed feedback using inline comments for ONLY issues, no praise inline comments.
    Use top-level comments for general observations or praise
    Do not be shy, I am a big boy and can handle criticism gracefully. I welcome feedback and suggestions.

    Review this PR against our team checklist:

    ## Code Quality
    - [ ] Code follows our style guide
    - [ ] No commented-out code
    - [ ] Meaningful variable names
    - [ ] DRY principle followed

    ## Testing
    - [ ] Unit tests for new functions
    - [ ] Integration tests for new endpoints
    - [ ] Edge cases covered
    - [ ] Test coverage > 80%

    ## Documentation
    - [ ] README updated if needed
    - [ ] API docs updated
    - [ ] Inline comments for complex logic
    - [ ] CHANGELOG.md updated

    ## Security
    - [ ] No hardcoded credentials
    - [ ] Input validation implemented
    - [ ] Proper error handling
    - [ ] No sensitive data in logs

    For each item, check if it is satisfied and comment on any that need attention.
    Post a summary comment with checklist results.

  # https://code.claude.com/docs/en/settings
  # https://www.schemastore.org/claude-code-settings.json
  settings:
    attribution:
      commit: 'Generated with JobsTaker'
      pr: ''
    permissions:
      allow:
        - mcp__github_inline_comment__create_inline_comment,
        - Bash(gh pr comment:*),
        - Bash(gh pr diff:*),
        - Bash(gh pr view:*),
        - Bash(grep .*),
        - Bash(rg .*),
        - Bash(npm run lint)
        - Bash(npm run test:*)
        - Bash(cargo .*)

      deny:
        - Bash(cargo publis.*)
      #   - Read(./.env)
      #   - Read(./.env.*)
      #   - Read(./secrets/**)
    env:
      CLAUDE_CODE_ENABLE_TELEMETRY: '0'
      OTEL_METRICS_EXPORTER: otlp
