name: Rust Check
on:
  workflow_call:
    inputs:
      ubuntu_packages:
        type: string
        required: false
        default: ""
      feature_matrix:
        type: string
        required: false
        default: '["default"]'
      extra_script_path:
        type: string
        default: ".github/ci-scripts/extra.sh"
        required: false
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  fmt:
    runs-on: ${{ vars.RUNNER }}
    name: nightly fmt
    steps:
      - name: Init
        uses: carteramesh/ci/.github/actions/rust-init@main
      - name: cargo fmt --check
        run: |
          cargo +nightly fmt --check --all
  clippy:
    runs-on: ${{ vars.RUNNER }}
    name: ${{ matrix.toolchain }} / clippy / ${{ matrix.features }}
    permissions:
      contents: read
      checks: write
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable]
        features: ${{ fromJSON(inputs.feature_matrix) }}
    steps:
      - name: Init
        uses: carteramesh/ci/.github/actions/rust-init@main
      - name: ${{ matrix.toolchain }} cargo clippy (${{ matrix.features }})
        uses: giraffate/clippy-action@v1
        with:
          reporter: "github-pr-check"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tool_name: clippy-${{ matrix.features }}
          clippy_flags: ${{ matrix.features != 'default' && format('--features {0}', matrix.features) || '' }}
  semver:
    runs-on: ${{ vars.RUNNER }}
    name: semver
    if: true
    steps:
      - name: Init
        uses: carteramesh/ci/.github/actions/rust-init@main
      - name: cargo-semver-checks
        uses: obi1kenobi/cargo-semver-checks-action@v2
        # with:
        # feature-group: ${{ matrix.features != 'default' && matrix.features || 'default-features' }}

  hack:
    # cargo-hack checks combinations of feature flags to ensure that features are all additive
    # which is required for feature unification
    runs-on: ${{ vars.RUNNER }}
    name: ubuntu / stable / features
    steps:
      - name: Init
        uses: carteramesh/ci/.github/actions/rust-init@main
      - name: cargo install cargo-hack
        uses: taiki-e/install-action@cargo-hack
      # intentionally no target specifier; see https://github.com/jonhoo/rust-ci-conf/pull/4
      # --feature-powerset runs for every combination of features
      - name: cargo hack
        run: cargo hack --feature-powerset check

  doc:
    runs-on: ${{ vars.RUNNER }}
    name: doc
    steps:
      - name: Init
        uses: carteramesh/ci/.github/actions/rust-init@main
      - name: cargo docs-rs
        run: |
          cargo +nightly docs-rs

  cargo_sort:
    runs-on: ${{ vars.RUNNER }}
    steps:
      - name: Init
        uses: carteramesh/ci/.github/actions/rust-init@main
      - name: Install cargo-sort
        run: cargo install --locked cargo-sort
      - name: Check `Cargo.toml` sort
        run: |
          if [ -f ./scripts/cargo-sort.sh ]; then
            ./scripts/cargo-sort.sh
          else
            cargo sort -c -g
          fi

  machete:
    runs-on: ${{ vars.RUNNER }}
    steps:
      - name: Init
        uses: carteramesh/ci/.github/actions/rust-init@main
      - name: Install `cargo-machete`
        run: cargo install cargo-machete
      - name: Check unused Cargo dependencies
        run: cargo machete
